version: '3'
services:
  django:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app